### ISSUE TITLE
History view shows empty rows for each day

### ISSUE THREAD

**Issue by fmsouza** [RioBus/android#50]
When accessing history view in the side menu after having already searched for something, the rows corresponding to each day are not clear that you should click in the row to show the searches for that day.

It could be solved with an arrow saying it can expand down.

**Comment by limazix** [comment]
There's a arrow on the left side. Not sure if I can change that easily.

BTW, this view is just for now. We'll change the history mechanism from the scratch.

**Comment by fmsouza** [comment]
The arrow does not show up correctly. Tested in a Samsung Galaxy Note 10.1 tablet running stock 5.1.1 android.

But do it really need to be full rewritten from scratch? The only problem is that it is 'ugly' right now, but it can be fixed.

**Comment by limazix** [comment]
First, the design was made for cellphones, so there is no guarantee that will work well for other devices. Please, install in a cellphone where it is meant to be. If it is still bad, ok, we'll check, otherwise it doesn't make sense.

And yes, the feature is not working well it must be recreated from the scratch.

**Comment by fmsouza** [comment]
Moved to #59.
